### ISSUE TITLE
Replace NX with Yarn workspaces

### ISSUE THREAD

**Issue by cedoor** [privacy-scaling-explorations/zk-groups#134]
**Tasks**:

- [x] Update ESlint conf
- [x] Update Jest conf
- [x] Merge `@zk-groups/contract-utils` & `@zk-groups/utils` and publish package
- [x] Create package.json files
  - [x] Libs
  - [x] Apps
  - [x] Create `start` command for contracts
- [x] Replace Webpack with NestJS CLI in the api component
- [x] Replace Webpack with `vite` in the FE projects
- [x] Replace scripts to bump versions and publish NPM packages with yarn commands
- [x] Set consistent deps among package.json files
- [x] Re-check configuration files: `tsconfig.json`, `jest.config.ts`, `.eslintrc.json`
- [x] Check Prettier and ESLint rules
- [x] Release new minor version
