### ISSUE TITLE
On-chain proof verification

### ISSUE THREAD

**Issue by cedoor** [privacy-scaling-explorations/zk-groups#84]
**Description**:

The ZK-Groups contract should be independent from the protocol used to verify proofs. For each protocol a new specific contract can be added.

**Tasks**:

- [x] Make `ZKGroups.sol` contract independent
- [x] Create specific contract to verify proofs with Semaphore
- [x] Update `contract-utils` lib
