### ISSUE TITLE
Use conventional commits to automatically generate changelogs and bump versions

### ISSUE THREAD

**Issue by cedoor** [privacy-scaling-explorations/zk-groups#94]
**Tasks**:

- [x] Configure `husky` & `commitlint` to check commits created without `yarn commit`
- [x] Configure `@zk-groups/contracts` properly
- [x] Create command to bump new versions (it should take the version as a argument and it should create a tag)
- [x] Create command to publish NPM packages (it should be run in a workflow on main branch)
- [x] Configure workflow with `changelogithub` to automatically generate cool release notes/changelogs based on tags

**Resources**:

- https://github.com/jscutlery/semver
- https://github.com/release-it/release-it
- https://github.com/changesets/changesets
- https://github.com/antfu/changelogithub
- https://github.com/antfu/bumpp
- https://github.com/semantic-release/semantic-release
- https://github.com/conventional-changelog/conventional-changelog
