### ISSUE TITLE
Start Hardhat network in the `dev` environment

### ISSUE THREAD

**Issue by cedoor** [privacy-scaling-explorations/zk-groups#97]
**Tasks**:

- [ ] Add `start` NX command to the `apps/contracts/project.json` file (compile/node/deploy)
- [ ] Create an env variable to set the Ethereum network
- [ ] Add Docker conf
